[package]
name = "android-tablet-bridge"
version = "0.1.0"
edition = "2024"

[dependencies]
adb_client = "2.0.6"
clap = { version = "4.5.23", features = ["derive"] }
input-linux = "0.7.1"
nix = "0.29.0"
nom = "7.1.3"
cli-table = "0.4.9"
pretty_assertions = "1.4.1"
